# Generated by Django 3.1.5 on 2021-04-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('owner', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=5)),
                ('asset_name', models.TextField()),
                ('asset_type', models.CharField(max_length=25)),
                ('transaction_type', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=45)),
                ('comments', models.TextField()),
                ('url', models.URLField()),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_related_trades', to='stocks.asset')),
                ('senator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_trades', to='stocks.senator')),
            ],
        ),
    ]
