# Generated by Django 3.0.7 on 2020-06-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('owner', models.CharField(choices=[('S', 'Self'), ('SP', 'Spouse')], max_length=6)),
                ('ticker', models.CharField(max_length=5)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('ST', 'Stock'), ('MS', 'Municipal Security'), ('O', 'Other Security'), ('CB', 'Corporate Bond')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sale')], max_length=5)),
                ('amount', models.CharField(choices=[('1', '1,001 - $15,000'), ('2', '$15,001 - $50,000'), ('3', '$50,001 - $100,000'), ('4', '$100,001 - $250,001'), ('5', '$250,001 - $500,000'), ('6', '$500,001 - $1,000,000'), ('7', '$1,000,001 - $5,000,000'), ('8', '$5,000,001 - $25,000,000'), ('9', '$25,000,001 - $50,000,000'), ('10', 'Over $50,000,000')], max_length=10)),
                ('comments', models.TextField()),
            ],
        ),
    ]
