# Generated by Django 3.1.5 on 2021-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='party',
            field=models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat'), ('I', 'Independent')], default='I', max_length=4),
        ),
    ]
