# Generated by Django 3.0.7 on 2020-06-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='senator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.Senator'),
        ),
    ]
