# Generated by Django 3.1.5 on 2021-04-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_senator_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='photo_url',
            field=models.URLField(default=''),
        ),
    ]
