# Generated by Django 3.0.7 on 2020-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_trade_senator'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='incumbent',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='senator',
            name='party',
            field=models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat'), ('I', 'Independent')], max_length=2),
        ),
    ]
