# Generated by Django 3.1.5 on 2021-04-07 21:21

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_senator_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='senator',
            name='state',
            field=localflavor.us.models.USStateField(default='AK', max_length=2),
        ),
    ]
