# Generated by Django 3.1.5 on 2021-10-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_senator_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
