# Generated by Django 3.0.7 on 2020-06-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20200618_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='incumbent',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], max_length=1),
        ),
    ]
