# Generated by Django 3.0.7 on 2020-07-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20200618_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='owner',
            field=models.CharField(choices=[('S', 'Self'), ('SP', 'Spouse'), ('J', 'Joint')], max_length=6),
        ),
        migrations.AlterField(
            model_name='trade',
            name='transaction_type',
            field=models.CharField(choices=[('P', 'Purchase'), ('FS', 'Sale (Full)'), ('PS', 'Sale (Partial)')], max_length=10),
        ),
    ]
