# Generated by Django 3.0.7 on 2020-07-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20200702_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senator',
            name='incumbent',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='party',
        ),
        migrations.RemoveField(
            model_name='senator',
            name='state',
        ),
    ]
