# Generated by Django 3.0.7 on 2020-07-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20200702_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='trade',
            name='owner',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='transaction_type',
            field=models.CharField(max_length=20),
        ),
    ]
