# Generated by Django 3.0.7 on 2020-07-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_auto_20200705_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='transaction_date',
            field=models.CharField(max_length=20),
        ),
    ]
