# Generated by Django 3.0.7 on 2020-07-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20200705_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='senator',
        ),
    ]
