# Generated by Django 3.0.7 on 2020-07-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_auto_20200705_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='transaction_type',
        ),
    ]
