# Generated by Django 3.0.7 on 2020-07-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_auto_20200705_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='asset_name',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='asset_type',
            field=models.CharField(default='N/A', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='owner',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='senator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.Senator'),
        ),
        migrations.AddField(
            model_name='trade',
            name='ticker',
            field=models.CharField(default='N/A', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='transaction_type',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
