# Generated by Django 3.1.5 on 2021-03-04 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.asset'),
        ),
    ]
